### ISSUE TITLE
[Bug] AttributeError: '...EnvParams' object has no attribute 'max_steps_in_episode'

### ISSUE THREAD

**Issue by axelbr** [keraJLi/rejax#9]
Some part of the code (evaluate.py, line 88), assume that the env params struct has a field `max_steps_in_episode`.

**Comment by keraJLi** [comment]
Hi @axelbr! 

The field `max_steps_in_episode` is defined in the base class [`gymnax.environments.environment.EnvParams`](https://github.com/RobertTLange/gymnax/blob/aef77d5c642ea48b95f34c51d05b8417d9450e15/gymnax/environments/environment.py#L22), and should therefore be defined in all Gymnax environments. I have therefore considered it part of the standard Gymnax interface.
If this leads to a bug with your code (e.g. you have defined `EnvParams` that don't inherit from this base class), a simple workaround would be to add the field to your struct.

**Comment by axelbr** [comment]
Thanks for the fast reply.
Hm, this isn't documented in Gymnax anywhere, but you are right. I did not notice the type bounds for the generic.
